### ISSUE TITLE
Custom report doesn't report correctly the time execution 

### ISSUE THREAD

**Issue by maxbetton** [bitrise-steplib/step-custom-test-results-export#10]
### Issue description

I have a problem with the reporting step at the time level. I have the impression that the time data of the given xml file is truncated.

for exemple with this xml file 

`<?xml version='1.0' encoding='UTF-8' ?>
<testsuites>
  <testsuite name="Pixel2-29-en-portrait" tests="13" failures="0" flakes="3" errors="0" skipped="0" time="333.564" timestamp="2021-05-11T01:22:42" hostname="localhost">`

the time result of this device should be 333.564 seconds (≈ 6min)
But the parser says 33s like you see. And this is the case in all cases.

<img width="809" alt="Capture d’écran 2021-05-11 à 10 13 59" src="https://user-images.githubusercontent.com/55984454/117782110-9c4f6780-b241-11eb-85bb-2019bc06fe00.png">

**Comment by Roland-Bak** [comment]
Hi there @maxbetton ,

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look?
🙂

**Comment by maxbetton** [comment]
Hello,
example of build : https://app.bitrise.io/build/2d90b5e79230396c#?tab=log
I have enable Support Acces 
Thanks :)
