### ISSUE TITLE
Adding Special Characters to the Test Name Breaks the Test Reports Addon

### ISSUE THREAD

**Issue by mjones-ebth** [bitrise-steplib/step-custom-test-results-export#12]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.1.3
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Issue description

Adding a special character to the "The name of the test" step input causes the Test Reports addon to break. Examples:

**Working**
https://app.bitrise.io/build/1bf7b06abe85a814#?tab=log
Test Name: Jest Tests

**Broken**
https://app.bitrise.io/build/f17ed6f398f953a2#?tab=log
Test Name: Jest Tests / React Testing Library

In both builds the log shows the step passing. However, if you click on "Test Reports" from the build page on the second build you get the following error: _"Test Reports wasn't configured correctly. Please make sure you configure it in the Workflow Editor. Get help for setting up Test Reports."_

Replicating this is pretty straightforward. Just add a special character to the test name (in the example above, removing the slash fixes the issue). 

### Bitrise info

- Build URL: https://app.bitrise.io/build/1bf7b06abe85a814#?tab=log / https://app.bitrise.io/build/f17ed6f398f953a2#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES

### Steps to reproduce

1. Add the Custom Test Results Export step to a relevant project
2. Add a special character (specifically a slash) to the test name step input.

**Comment by Roland-Bak** [comment]
Hi Matthew! 👋😁

I created a task for this in the dev team's backlog, and I already saw that the ticket was updated so they should be aware of this and will hopefully work it out as soon as they can 🙂

Good to hear from you, don't be a stranger! 😉
