### ISSUE TITLE
Step fails if test reports have not been found

### ISSUE THREAD

**Issue by motorro** [bitrise-steplib/step-custom-test-results-export#8]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.1.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Step fails the build if test results are not found. It will be great if it could succeed (at least optionally) if no results are generated and uploaded.

In my case (see build log below) all tasks completed from gradle cache so test-results were not generated in target directory.
I think it is ok to not to fail in that case. At least as soon as test result upload is a kind of supplementary thing (IMO)

### Bitrise info

- Build URL: https://app.bitrise.io/build/391ffbda706c0403#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 
```
+------------------------------------------------------------------------------+
| (8) custom-test-results-export@0                                             |
+------------------------------------------------------------------------------+
| id: custom-test-results-export                                               |
| version: 0.1.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-03-10T17:51:06Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- TestName: Unit tests
- BasePath: /bitrise/src/build/
- SearchPattern: test-results.xml
- TestResultsDir: /tmp/test_results667550410/test_result453824208
- VerboseLog: false
Invalid base path /bitrise/src/build/: lstat /bitrise/src/build/: no such file or directory
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | custom-test-results-export@0 (exit code: 1)                   | 2.17 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...com/bitrise-steplib/step-custom-test-results-export/issues |
| Source: https://github.com/bitrise-steplib/step-custom-test-results-export   |
+---+---------------------------------------------------------------+----------+
```

### Steps to reproduce

1. Enable gradle cache:
```
org.gradle.caching=true
```
2. Run unit tests
3. Run them again to get results from cache:
```
> Task :runDataUnitTests UP-TO-DATE
> Task :runDomainUnitTests UP-TO-DATE
```
4. No test is generated in build folders
5. The upload step fails

**Comment by ofalvai** [comment]
Hey @motorro,

Based on the error message, it looks like the problem is not the test results directory, but the base path `/bitrise/src/build`. This folder should be present even if tasks were cached. Maybe you run `:clean` at some point in your workflow?

**Comment by motorro** [comment]
@ofalvai 
I've included a gradle task to pre-create the directory so it is always there now
Unfortunately, I can't figure out how to setup search-pattern correctly.

The following doesn't work:
```
    - custom-test-results-export@0:
        inputs:
          - search_pattern: test-results.xml
          - base_path: $BITRISE_SOURCE_DIR/build/
          - test_name: Unit tests
```
Can't find file although it is there:
````````
+------------------------------------------------------------------------------+
| (8) List $BITRISE_SOURCE_DIR/build/                                          |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.6                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2021-04-10T16:34:20Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
+ ls /bitrise/src/build/
kotlin
test-results
test-results.xml
|                                                                              |
+---+---------------------------------------------------------------+----------+
| [32;1m✓[0m | [32;1mList $BITRISE_SOURCE_DIR/build/[0m                               | 1.63 sec |
+---+---------------------------------------------------------------+----------+

                                          ▼

+------------------------------------------------------------------------------+
| (9) custom-test-results-export@0                                             |
+------------------------------------------------------------------------------+
| id: custom-test-results-export                                               |
| version: 0.1.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-04-10T16:34:21Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
[34;1mConfig:
[0m- TestName: Unit tests
- BasePath: /bitrise/src/build/
- SearchPattern: test-results.xml
- TestResultsDir: /tmp/test_results937655723/test_result558582516
- VerboseLog: false
[31;1mPattern test-results.xml did not match any files within path /bitrise/src/build/[0m
|                                                                              |
```

**Comment by ofalvai** [comment]
The search pattern should simply be `*.xml`.

I did some testing and looks like that pattern should always be a pattern (with a `*` symbol), specifying the full file name doesn't work for some reason. We'll look into why this is the case, in the meantime please use `*.xml` or a similar pattern to match the file.

**Comment by motorro** [comment]
@ofalvai, thanks for clarification.
Will use a pattern then.
The support for exact file name will be great as have to combine multiple results into one for export (your plugin accepts only one file). So if the pattern is used I have to either delete combined results explicitly before exporting or to hope the step selects the correct file :)

**Comment by ofalvai** [comment]
@motorro I realized there is a way to define a single file without wildcards:
- point the base path input to the file itself: `build/test-results.xml`
- use `*` as the search pattern input

We updated the description in #9 to make it a bit more clear.

**Comment by motorro** [comment]
@ofalvai, thanks for the tip! The build passes now and the step doesn't fail, but I can't figure out the correct format for add-on to parse. Although the result seems to be uploaded the addon still gives me "Test Reports wasn't configured correctly. Please make sure you configure it in the Workflow Editor"
Here is the build (support enabled today): https://app.bitrise.io/build/72dba04dd019d040#?tab=log
Step config:
```
- custom-test-results-export@0:
        inputs:
        - search_pattern: "*"
        - base_path: "$BITRISE_SOURCE_DIR/build/test-results.xml"
        - test_name: Unit
```
Step result:
```
+------------------------------------------------------------------------------+

| (9) custom-test-results-export@0                                             |
+------------------------------------------------------------------------------+
| id: custom-test-results-export                                               |
| version: 0.1.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-04-20T12:31:45Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
- TestName: Unit
- BasePath: /bitrise/src/build/test-results.xml
- SearchPattern: *
- TestResultsDir: /tmp/test_results140954740/test_result204777089
- VerboseLog: false
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | custom-test-results-export@0                                  | 3.18 sec |
+---+---------------------------------------------------------------+----------+
```
Here is the [link](https://drive.google.com/file/d/197PHoJg-qXHoWjroW8NjxABw02suKX36/view?usp=sharing) to combined test-results.
Thanks a lot!

**Comment by ofalvai** [comment]
@motorro Looks like you are missing the Deploy to Bitrise.io step at the end of your workflow. This step is responsible (among other things) for sending the files to the Test Results add-on.

**Comment by motorro** [comment]
@ofalvai, yes!
Thank you very much for your support!
